name: Unit Tests

on: 
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-shell-script:
    runs-on: self-hosted

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Get changed files
      id: changed_files
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD)"

    - name: Run unit test
      if: ${{ !contains(join(github.event.files, ', '), 'docs/,.md') }}
      run: |
        containers=$(docker ps -aqf "name=^chatlearn_ut_")
        if [[ -n "$containers" ]]; then
            docker rm $containers -f
        fi
        docker pull $UT_IMAGE
        docker run -v $PWD:$PWD -w $PWD --name chatlearn_ut_$(date '+%d_%m_%Y_%H_%M_%S') --net host --ipc host --shm-size 80G -t --rm --gpus all $UT_IMAGE bash -c 'make test'

    - name: Docs-Only Changes
      if: ${{ contains(join(github.event.files, ', '), 'docs/,.md') }}
      run: |
        echo "Documentation or .md file(s) changed. Skipping unit tests."

      env: 
        UT_IMAGE: ${{ secrets.UT_IMAGE }}
